## Recodificação DPs

library(tidyverse)

#código 

limpeza_dp <- function(coluna) {
  dplyr::case_when(
    coluna %in% c("101º D.P. JARDIM IMBUIAS", "101º D.P. JDIM IMBUIAS") ~ "101 DP - Jardim das Imbuias",
    coluna == "81º D.P. BELEM" ~ "081 DP - Belém",
    coluna == "73º D.P. JACANA" ~ "073 DP - Jaçanã",               
    coluna == "64º D.P. CID.AE CARVALHO" ~ "064 DP - Cidade A E Carvalho",         
    coluna == "90º D.P. PQ. NOVO MUNDO" ~ "090 DP - Parque Novo Mundo",         
    coluna == "103º D.P. COHABII/ITAQU." ~ "103 DP - Cohab Itaquera",        
    coluna == "39º D.P. VILA GUSTAVO" ~ "039 DP - Vila Gustavo",        
    coluna == "11º D.P. SANTO AMARO" ~ "011 DP - Santo Amaro",            
    coluna == "54º D.P. CID. TIRADENTES" ~ "054 DP - Cidade Tiradentes",         
    coluna == "08º D.P. BRAS" ~ "008 DP - Brás",                     
    coluna == "36º D.P. VILA MARIANA" ~ "036 DP - Vila Mariana",            
    coluna == "59º D.P. JARDIM DOS IPES" ~ "059 DP - Jardim Noemia",       
    coluna == "98º D.P. JARDIM MIRIAM" ~ "098 DP - Jardim Míriam",            
    coluna == "17º D.P. DOUTOR ALDO GALIANO" ~ "017 DP - Ipiranga",    
    coluna == "72º D.P. VILA PENTEADO" ~ "072 DP - Vila Penteado",         
    coluna == "75º D.P. JARDIM ARPOADOR" ~ "075 DP - Jardim Arpoador",        
    coluna == "69º D.P. TEOTONIO VILELA" ~ "069 DP - Teotônio Vilela",        
    coluna == "37º D.P. CAMPO LIMPO" ~ "037 DP - Campo Limpo",            
    coluna == "67º D.P. JARDIM ROBRU" ~ "067 DP - Jardim Robru",          
    coluna == "62º D.P. ERMELINO MATARAZZO" ~ "062 DP - Ermelino Matarazzo",      
    coluna == "06º D.P. CAMBUCI" ~  "006 DP - Cambuci",                 
    coluna == "25º D.P. PARELHEIROS" ~  "025 DP - Parelheiros",             
    coluna == "49º D.P. SAO MATEUS" ~  "049 DP - São Mateus",               
    coluna %in% c("15ª DP DR LUCIANO H BEIGUELMAN", "15º D.P. DR. LUC. H BEIGUELMAN")  ~ "015 DP - Itaim Bibi", 
    coluna == "68º D.P. LAGEADO" ~  "068 DP - Lajeado",                 
    coluna == "16º D.P. VILA CLEMENTINO" ~  "016 DP - Vila Clementino",       
    coluna == "45º D.P. V BRASILANDIA"  ~ "045 DP - Vila Brasilândia",          
    coluna == "41º D.P. VILA RICA" ~ "041 DP - Vila Rica",               
    coluna == "04º D.P. CONSOLAÇÃO" ~ "004 DP - Consolação",             
    coluna == "63º D.P. VILA JACUI" ~ "063 DP - Vila Jacuí",             
    coluna == "38º D.P. VILA AMALIA" ~ "038 DP - Vila Amália",             
    coluna %in% c("95º D.P. HELIÓPOLIS", "95º D.P. HELIOPOLIS") ~ "095 DP - Heliópolis",            
    coluna %in% c("27º DP \"DR. IGNÁCIO FRANCISCO\"", "27º D.P. IBIRAPUERA") ~  "027 DP - Campo Belo", 
    coluna == "74º D.P. PARADA TAIPAS"  ~  "074 DP - Jaraguá",          
    coluna == "10º D.P. PENHA DE FRANCA"  ~ "010 DP - Penha de França",      
    coluna == "34º D.P. MORUMBI" ~ "034 DP - Vila Sonia",                 
    coluna == "35º D.P. JABAQUARA" ~ "035 DP - Jabaquara",              
    coluna == "40º D.P. VILA STA MARIA" ~  "040 DP - Vila Santa Maria",          
    coluna == "50º D.P. ITAIM PAULISTA" ~ "050 DP - Itaim Paulista",         
    coluna == "33º D.P. PIRITUBA" ~  "033 DP - Pirituba",               
    coluna == "70º D.P. VILA EMA" ~  "070 DP - Vila Ema",              
    coluna == "43º D.P. CIDADE ADEMAR" ~ "043 DP - Cidade Ademar",          
    coluna == "48º D.P. CIDADE DUTRA" ~ "048 DP - Cidade Dutra",           
    coluna == "55º D.P. PARQUE S.RAFAEL" ~ "055 DP - Parque São Rafael",        
    coluna == "56º D.P. VILA ALPINA" ~  "056 DP - Vila Alpina",             
    coluna %in% c("92º D.P. PQ. SANTO ANTONIO", "92º D.P. P. STO ANTONIO") ~ "092 DP - Parque Santo Antônio",       
    coluna == "01º D.P. SE" ~ "001 DP - Sé",                     
    coluna == "91º D.P. CEASA" ~ "091 DP - Ceagesp",                   
    coluna == "44º D.P. GUAIANAZES" ~ "044 DP - Guaianazes",            
    coluna == "51º D.P. RIO PEQUENO" ~ "051 DP - Butantã",            
    coluna == "22º D.P. SAO MIGUEL PTA" ~ "022 DP - São Miguel Paulista",       
    coluna == "46º D.P. PERUS" ~ "046 DP - Perus",                   
    coluna == "85º D.P. JARDIM MIRNA" ~  "085 DP - Jardim Mirna",           
    coluna == "24º D.P. PONTE RASA" ~  "024 DP - Ponte Rasa",             
    coluna == "52º D.P. PARQUE S.JORGE" ~  "052 DP - Parque São Jorge",         
    coluna == "83º D.P. PARQUE BRISTOL" ~ "083 DP - Parque Bristol",         
    coluna == "99º D.P. CAMPO GRANDE" ~ "099 DP - Campo Grande",            
    coluna == "87º D.P. V. P. BARRETO" ~ "087 DP - Vila Pereira Barreto",            
    coluna == "97º D.P. AMERICANOPOLIS" ~ "097 DP - Americanópolis",          
    coluna == "42º D.P. PARQUE S. LUCAS" ~ "042 DP - Parque São Lucas",        
    coluna == "53º D.P. PARQUE DO CARMO" ~ "053 DP - Parque do Carmo",         
    coluna == "47º D.P. CAPAO REDONDO" ~ "047 DP - Capão Redondo",          
    coluna == "65º D.P. ARTUR ALVIM" ~ "065 DP - Artur Alvim",          
    coluna == "12º D.P. PARI" ~ "012 DP - Pari",                   
    coluna == "29º D.P. VILA PRUDENTE" ~  "029 DP - Vila Diva",          
    coluna == "89º D.P. JARDIM TABOAO" ~  "089 DP - Portal do Morumbi",          
    coluna == "93º D.P. JAGUARÉ" ~ "093 DP - Jaguaré",                
    coluna == "19º D.P. VILA MARIA" ~ "019 DP - Vila Maria",               
    coluna == "21º D.P. VILA MATILDE" ~ "021 DP - Vila Matilde",          
    coluna == "96º D.P. MONÇÕES" ~ "096 DP - Monções",                 
    coluna == "14º D.P. PINHEIROS" ~ "014 DP - Pinheiros",            
    coluna == "18º D.P. ALTO DA MOOCA" ~ "018 DP - Alto da Moóca",         
    coluna == "28º D.P. FREGUESIA DO O"  ~ "028 DP - Freguesia do Ó",        
    coluna %in% c("66º D.P. JDIM ARICANDUVA","66º D.P. JARDIM ARICANDUVA") ~ "066 DP - Vale do Aricanduva",         
    coluna == "03º D.P. CAMPOS ELISEOS" ~ "003 DP - Campos Elísios",        
    coluna == "20º D.P. AGUA FRIA" ~ "020 DP - Água Fria",             
    coluna == "31º D.P. VILA CARRAO" ~ "031 DP - Vila Carrão",            
    coluna == "13º D.P. CASA VERDE"  ~ "013 DP - Casa Verde",           
    coluna == "102º D.P. SOCORRO" ~ "102 DP - Socorro",               
    coluna == "30º D.P. TATUAPE" ~  "030 DP - Tatuapé",               
    coluna == "09º D.P. CARANDIRU" ~ "009 DP - Carandiru",           
    coluna %in% c("100º D.P. JDIM HERCULANO", "100º D.P. JARDIM HERCULANO") ~ "100 DP - Jardim Herculano",        
    coluna == "78º D.P. JARDINS" ~ "078 DP - Jardins",                 
    coluna == "07º D.P. LAPA" ~ "007 DP - Lapa",                    
    coluna == "32º D.P. ITAQUERA" ~ "032 DP - Itaquera",              
    coluna == "77º D.P. SANTA CECILIA" ~ "077 DP - Santa Cecília",         
    coluna == "23º D.P. PERDIZES" ~ "023 DP - Perdizes",               
    coluna == "26º D.P. SACOMA" ~ "026 DP - Sacomã",                 
    coluna == "80º D.P. VILA JOANIZA" ~ "080 DP - Vila Joaniza",          
    coluna == "57º D.P. PARQUE DA MOOCA" ~ "057 DP - Parque da Moóca",        
    coluna == "58º D.P. VILA FORMOSA" ~ "058 DP - Vila Formosa",            
    coluna == "05º D.P. ACLIMACAO" ~ "005 DP - Aclimação",              
    coluna == "69 D.P. - TEOTONIO VILELA" ~ "069 DP - Teotônio Vilela",      
    coluna == "02º D.P. BOM RETIRO" ~  "002 DP - Bom Retiro", 
    TRUE ~ as.character(coluna)
  )
}
