## Recodificação municipios 

library(tidyverse)
mdip_ssp <- readRDS("../data-raw/mdip_ssp.rds")
mdip_mp <- readRDS("../data-raw/mdip_mp.rds")

#código 

limpeza_municipio<- function(coluna) {
  dplyr::case_when(
  coluna == "Aguai" ~ "Aguaí",
  coluna %in% c("Aguas De S. Barbara", "Águas De Santa Bárbara") ~ "Águas de Santa Bárbara",
  coluna == "Águas De Lindóia" ~ "Águas de Lindóia",
  coluna == "Apiai" ~ "Apiaí",
  coluna == "Aracariguama" ~ "Araçariguama",
  coluna == "Aracatuba" ~ "Araçatuba",
  coluna %in% c("Aracoiaba Da Serra", "Araçoiaba Da Serra") ~ "Araçoiaba da Serra",
  coluna == "Arapei" ~ "Arapeí",
  coluna == "Aruja" ~ "Arujá",
  coluna == "Avare" ~ "Avaré",
  coluna == "Bady Bassit" ~ "Bady Bassitt",
  coluna == "Barra Do Turvo" ~ "Barra do Turvo",
  coluna == "Bernardino De Campos" ~ "Bernardino de Campos",
  coluna == "Biritiba-Mirim" ~ "Biritiba Mirim",
  coluna %in% c("Bom Jesus Dos Perdoes", "Bom Jesus Dos Perdões") ~ "Bom Jesus dos Perdões",
  coluna == "Braganca Paulista" ~ "Bragança Paulista",
  coluna == "Cacapava" ~ "Caçapava",
  coluna == "Cafelandia" ~ "Cafelândia",
  coluna %in% c("Campos Do Jordao", "Campos Do Jordão") ~ "Campos do Jordão",
  coluna == "Campos Novos Paul." ~ "Campos Novos Paulista",
  coluna == "Cananeia" ~ "Cananéia",
  coluna == "Candido Mota" ~ "Cândido Mota",
  coluna == "Capao Bonito" ~ "Capão Bonito",
  coluna == "Capela Do Alto" ~ "Capela do Alto",
  coluna == "Carapicuiba" ~ "Carapicuíba",
  coluna == "Catigua" ~ "Catiguá",
  coluna == "Cesario Lange" ~ "Cesário Lange",
  coluna == "Corumbatai" ~ "Corumbataí",
  coluna == "Cosmopolis" ~ "Cosmópolis",
  coluna == "Cubatao" ~ "Cubatão",
  coluna == "Embu-Guacu" ~ "Embu-Guaçu",
  coluna == "Embu Das Artes" ~ "Embu das Artes",
  coluna %in% c("Espirito Sto. Pinhal", "Espírito Santo Do Pinhal") ~ "Espírito Santo do Pinhal",
  coluna == "Fernandopolis" ~ "Fernandópolis",
  coluna == "Ferraz De Vasconcelos" ~ "Ferraz de Vasconcelos",
  coluna == "Florida Paulista" ~ "Flórida Paulista",
  coluna == "Franco Da Rocha" ~ "Franco da Rocha",
  coluna == "Gaviao Peixoto" ~ "Gavião Peixoto",
  coluna == "Guaira" ~ "Guaíra",
  coluna == "Guapiacu" ~ "Guapiaçu",
  coluna == "Guaracai" ~ "Guaraçaí",
  coluna == "Guaratingueta" ~ "Guaratinguetá",
  coluna == "Guarei" ~ "Guareí",
  coluna == "Guaruja" ~ "Guarujá",
  coluna == "Hortolandia" ~ "Hortolândia",
  coluna == "Ibira" ~ "Ibirá",
  coluna == "Ibiuna" ~ "Ibiúna",
  coluna == "Igarata" ~ "Igaratá",
  coluna == "Inubia Paulista" ~ "Inúbia Paulista",
  coluna == "Ipero" ~ "Iperó",
  coluna == "Ipeuna" ~ "Ipeúna",
  coluna == "Ipigua" ~ "Ipiguá",
  coluna == "Iracemapolis" ~ "Iracemápolis",
  coluna == "Itai" ~ "Itaí",
  coluna == "Itanhaem" ~ "Itanhaém",
  coluna == "Itapecerica Da Serra" ~ "Itapecerica da Serra",
  coluna == "Itapirapua Paulista" ~ "Itapirapuã Paulista",
  coluna == "Jacarei" ~ "Jacareí",
  coluna == "Jaguariuna" ~ "Jaguariúna",
  coluna == "Jardinopolis" ~ "Jardinópolis",
  coluna == "Jau" ~ "Jaú",
  coluna == "Jose Bonifacio" ~ "José Bonifácio",
  coluna == "Jundiai" ~ "Jundiaí",
  coluna == "Juquia" ~ "Juquiá",
  coluna == "Lavinia" ~ "Lavínia",
  coluna == "Lencois Paulista" ~ "Lençóis Paulista",
  coluna %in% c("Lourenço Da Serra", "São Lourenço Da Serra") ~ "São Lourenço da Serra",
  coluna == "Mairipora" ~ "Mairiporã",
  coluna == "Maracai" ~ "Maracaí",
  coluna == "Marilia" ~ "Marília",
  coluna == "Martinopolis" ~ "Martinópolis",
  coluna == "Matao" ~ "Matão",
  coluna == "Maua" ~ "Mauá",
  coluna %in% c("Mineiros Do Tiete", "Mineiros Do Tietê") ~ "Mineiros do Tietê",
  coluna == "Mogi Das Cruzes" ~ "Mogi das Cruzes",
  coluna == "Mogi-Guacu" ~ "Mogi Guaçu",
  coluna == "Mogi-Mirim" ~ "Mogi Mirim",
  coluna == "Mongagua" ~ "Mongaguá",
  coluna == "Monte Aprazivel" ~ "Monte Aprazível",
  coluna == "Nova Alianca" ~ "Nova Aliança",
  coluna == "Olimpia" ~ "Olímpia",
  coluna == "Orlandia" ~ "Orlândia",
  coluna == "Paraguacu Paulista" ~ "Paraguaçu Paulista",
  coluna == "Pariquera-Acu" ~ "Pariquera-Açu",
  coluna == "Pauliceia" ~ "Paulicéia",
  coluna == "Paulinia" ~ "Paulínia", 
  coluna == "Paulo De Faria" ~  "Paulo de Faria", 
  coluna == "Pedro De Toledo" ~ "Pedro de Toledo",
  coluna == "Peruibe" ~ "Peruíbe", 
  coluna == "Pilar Do Sul" ~ "Pilar do Sul", 
  coluna == "Pirapora Do Bom Jesus"  ~ "Pirapora do Bom Jesus",  
  coluna == "Poa" ~ "Poá",
  coluna == "Pongai" ~ "Pongaí",
  coluna == "Pradopolis" ~  "Pradópolis", 
  coluna == "Presidente Epitacio" ~ "Presidente Epitácio",
  coluna == "Quata" ~  "Quatá",
  coluna == "Ribeirao Branco" ~ "Ribeirão Branco",                       
  coluna == "Ribeirao Grande" ~ "Ribeirão Grande",
  coluna == "Ribeirao Pires" ~ "Ribeirão Pires",
  coluna == "Ribeirao Preto" ~ "Ribeirão Preto",
  coluna == "Rincao" ~ "Rincão",
  coluna == "Rinopolis" ~ "Rinópolis",
  coluna == "Rio Das Pedras" ~ "Rio das Pedras",
  coluna == "Rio Grande Da Serra" ~ "Rio Grande da Serra",
  coluna == "Rubiacea" ~ "Rubiácea", 
  coluna == "S.andre" ~ "Santo André",  
  coluna %in% c("S.barbara D Oeste", "Santa Bárbara D'oeste") ~ "Santa Bárbara d'Oeste",  
  coluna %in% c("S.bernardo Do Campo", "São Bernardo Do Campo") ~"São Bernado do Campo",
  coluna %in% c( "S.caetano Do Sul", "São Caetano Do Sul") ~ "São Caetano do Sul",
  coluna == "S.carlos" ~"São Carlos",
  coluna == "S.cruz Da Conceicao" ~ "Santa Cruz da Conceição",
  coluna %in% c("S.cruz Das Palmeiras", "Santa Cruz Das Palmeiras") ~ "Santa Cruz das Palmeiras", 
  coluna == "S.cruz Do Rio Pardo" ~ "Santa Cruz do Rio Pardo",
  coluna == "S.gertrudes" ~"Santa Gertrudes",
  coluna == "S.isabel" ~ "Santa Isabel",
  coluna == "S.joaquim Da Barra" ~ "São Joaquim da Barra",
  coluna %in% c("S.jose Do Rio Preto", "São José Do Rio Preto") ~ "São José do Rio Preto",
  coluna %in% c("S.jose Dos Campos", "São José Dos Campos") ~ "São José dos Campos",
  coluna == "S.luis Do Paraitinga" ~ "São Luiz do Paraitinga",
  coluna == "S.miguel Arcanjo" ~ "São Miguel Arcanjo",
  coluna == "S.paulo" ~ "São Paulo",
  coluna == "S.pedro" ~ "São Pedro",
  coluna == "S.roque" ~ "São Pedro",
  coluna == "S.rosa De Viterbo" ~ "Santa Rosa de Viterbo",
  coluna == "S.sebastiao" ~ "São Sebastião",
  coluna == "S.simao" ~ "São Simão",
  coluna == "S.vicente" ~ "São Vicente",
  coluna == "Salesopolis" ~ "Salesópolis",
  coluna == "Salto De Pirapora" ~ "Salto de Pirapora",
  coluna == "Santa Maria Da Serra" ~ "Santa Maria da Serra",
  coluna == "Santana De Parnaiba" ~ "Santana de Parnaíba",
  coluna == "Sao Joao Da Boa Vista" ~ "São João da Boa Vista",
  coluna == "Sertaozinho" ~ "Sertãozinho",
  coluna == "Sumare" ~ "Sumaré",
  coluna %in% c("Taboao Da Serra", "Taboão Da Serra") ~ "Taboão da Serra",
  coluna == "Tapirai" ~ "Tapiraí", 
  coluna == "Taubate" ~ "Taubaté",
  coluna == "Tatui" ~ "Tatuí",
  coluna == "Tiete" ~ "Tietê",
  coluna == "Tremembe" ~ "Tremembé",
  coluna == "Torre De Pedra" ~ "Torre de Pedra",
  coluna == "Tupa" ~ "Tupã",
  coluna == "Varzea Paulista" ~ "Várzea Paulista",
  TRUE ~ as.character(coluna)
)
}

