---
title: "limpeza_mdip_ssp_mp"
author: "Mayra Pinheiro"
date: "2023-03-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(readxl)

source("../R/limpeza_municipio.R")
```

```{r bancos mdip, echo=FALSE, warning=FALSE}
mdip_13<- read_excel('../data-raw/MDIP_2013_2022.xlsx', sheet = "2013", col_types = c("text","text", "text", "text", "text", "text", "text", "numeric", "numeric", "date","text", "numeric", "text", "text", "text", "text", "date", "date", "text", "text", "text", "text", "text", "text", 
"text", "numeric", "date", "text", "text", "text")) |> janitor::clean_names()

mdip_14<- read_excel("../data-raw/MDIP_2013_2022.xlsx", sheet = "2014", col_types = c("text","text", "text", "text", "text", "text", "text", "numeric", "numeric", "date","text", "numeric", "text", "text", "text", "text", "date", "date", "text", "text", "text", "text", "text", "text", 
"text", "numeric", "date", "text", 
 "text", "text")) |> janitor::clean_names()

mdip_15<- read_excel("../data-raw/MDIP_2013_2022.xlsx", sheet = "2015", col_types = c("text","text", "text", "text", "text", "text", "text", "numeric", "numeric", "date","text", "numeric", "text", "text", "text", "text", "date", "date", "text", 
"text", "text", "text", "text", "text", 
"text", "numeric", "date", "text", 
 "text", "text")) |> janitor::clean_names()

mdip_16<- read_excel("../data-raw/MDIP_2013_2022.xlsx", sheet = "2016",  col_types = c("text","text", "text", "text", "text", "text", "text", "numeric", "numeric", "date","text", "numeric", "text", "text", "text", "text", "date", "date", "text", "text", "text", "text", "text", "text", 
"text", "numeric", "date", "text", 
 "text", "text")) |> janitor::clean_names()

mdip_17<- readxl::read_excel("../data-raw/MDIP_2013_2022.xlsx", sheet = "2017",  col_types = c("text","text", "text", "text", "text", "text", "text", "numeric", "numeric", "date","text", "numeric", "text", "text","text", "text", "date", "date", "text","text", "text", "text", "text", "text", 
"text", "numeric", "date", "text", 
 "text", "text")) |> janitor::clean_names()

mdip_18<- readxl::read_excel("../data-raw/MDIP_2013_2022.xlsx", sheet = "2018", col_types = c("text","text", "text", "text", "text", "text", "text", "numeric", "numeric", "date","text", "numeric", "text", "text","text", "text", "date", "date", "text", "text", "text", "text", "text", "text", 
"text", "numeric", "date", "text", 
 "text", "text")) |> janitor::clean_names()

mdip_19<- readxl::read_excel("../data-raw/MDIP_2013_2022.xlsx", sheet = "2019",  col_types = c("text","text", "text", "text", "text", "text", "text", "numeric", "numeric", "date","text", "numeric", "text", "text", "text", "text", "date", "date", "text", "text", "text", "text", "text", "text", "text", "numeric", "date", "text", 
 "text", "text")) |> janitor::clean_names()

mdip_20<- readxl::read_excel("../data-raw/MDIP_2013_2022.xlsx", sheet = "2020",  col_types = c("text","text", "text", "text", "text", "text", "text", "numeric", "numeric", "date","text", "numeric", "text", "text","text", "text", "date", "date", "text", "text", "text", "text", "text", "text", 
"text", "numeric", "date", "text", 
 "text", "text")) |> janitor::clean_names()

mdip_21<- readxl::read_excel("../data-raw/MDIP_2013_2022.xlsx", sheet = "2021", col_types = c("text","text", "text", "text", "text", "text", "text", "numeric", "numeric", "date","text", "numeric", "text", "text","text", "text", "date", "date", "text", "text", "text", "text", "text", "text", 
"text", "numeric", "date", "text", 
 "text", "text")) |> janitor::clean_names()

mdip_22<- readxl::read_excel("../data-raw/MDIP_2013_2022.xlsx", sheet = "2022", col_types = c("text","text", "text", "text", "text", "text", "text", "numeric", "numeric", "date","text", "numeric", "text", "text","text", "text", "date", "date", "text", "text", "text", "text", "text", "text", 
"text", "numeric", "date", "text", 
 "text", "text")) |> janitor::clean_names()

mdip_ssp <- dplyr::bind_rows(mdip_13, mdip_14, mdip_15, mdip_16, mdip_17, mdip_18, mdip_19, mdip_20, mdip_21, mdip_22)

mdip_mp <- readxl::read_excel("../data-raw/letalidade_policial.xlsx", sheet = "LETALIDADE", col_types = c("text", 
        "text", "date", "date", "text", "text", 
        "text", "text", "text", "text", "text", 
        "numeric", "text", "numeric"))|> janitor::clean_names()

estim_pop <- readxl::read_excel("../data-raw/estim_pop_sp.xls") |> 
   janitor::clean_names()

```

```{r,limpeza, echo=FALSE, warning=FALSE }
#cria a coluna ano na base mdip_mp
mdip_mp <- mdip_mp |> mutate(ano = str_sub(data, end = 4))

#limpa hora mp
mdip_mp <- mdip_mp |> mutate(hora = str_sub(hora,  start = 12))

#limpa hora ssp
mdip_ssp <- mdip_ssp |> mutate(hora_fato = str_sub(hora_fato,  start = 12))

#limpando as variáveis de locais 
mdip_ssp$municipio_circunscricao <- str_to_title(mdip_ssp$municipio_circunscricao)
mdip_mp$cidade <- str_to_title(mdip_mp$cidade)
mdip_mp$estado <- str_to_title(mdip_mp$estado)
mdip_mp$bairro <- str_to_title(mdip_mp$bairro)
mdip_ssp$logradouro <- str_to_title(mdip_ssp$logradouro)
mdip_ssp$profissao <- str_to_title(mdip_ssp$profissao)
mdip_ssp$municipio_elaboracao <- str_to_title(mdip_ssp$municipio_elaboracao)
mdip_ssp$municipio_circunscricao <- str_to_title(mdip_ssp$municipio_circunscricao)

# limpar coorporação na base do MP (que vem com dados de GCM, PF, etc)

mdip_mp <- mdip_mp |> 
  mutate(forca_limpo = case_when
  (forca %in% c("PM", "PM-GCM", "PM/GCM JUNDIAÍ", "PM/GCM") ~ "PM",
    forca %in% c("PC", "PC-GCM") ~ "PC",
    forca %in% c("PC-PM", "PM-PC") ~ "PM-PC",
    TRUE ~ as.character(forca))) |> 
  filter((forca_limpo %in% c("PM", "PC", "PM-PC")))

#torna todas as linhas uma observação 
#(cria um indice de replicação a partir da var. vitimas)
 idx <- rep(1:nrow(mdip_mp), mdip_mp$vitimas)
#replica no banco os casos com mais de uma vitima
 mdip_mp <- mdip_mp[idx,]
 
#cria RDO para ssp
mdip_ssp <- mdip_ssp |>mutate(rdo = paste(num_bo, ano_bo, sep= "/"))

#função para limpeza de municipios

mdip_ssp <- mdip_ssp |>
  mutate(municipio_limpo = limpeza_municipio(municipio_circunscricao))

mdip_mp <- mdip_mp |>
  mutate(municipio_limpo = limpeza_municipio(cidade))

# renomeia cidade/nome_do_municipio 
estim_pop <- estim_pop |>  rename(municipio_limpo = nome_do_municipio)

#Une os bancos
mdip_rdo<- merge(mdip_ssp, mdip_mp, by = "rdo", all = TRUE)

mdip_ssp_total<- merge(mdip_ssp, estim_pop, by = "municipio_limpo", all = TRUE)
mdip_mp_total<- merge(mdip_mp, estim_pop, by = "municipio_limpo", all = TRUE)

#limpa casos com NAs(usa rdo como var referência)

mdip_mp_total <- mdip_mp[complete.cases(mdip_mp$rdo), ]
mdip_ssp_total <- mdip_ssp[complete.cases(mdip_ssp$rdo), ]

#Cria coluna para join
mdip_ssp <- mdip_ssp_total|> mutate(var_join = paste(data_fato, hora_fato, municipio_limpo, sep ="/" )) 

mdip_mp <- mdip_mp_total|>  mutate(var_join = paste(data, hora, municipio_limpo, sep ="/" ))

mdip_ssp17<- mdip_ssp |> filter(ano_estatistica > 2017)
mdip_mp17<- mdip_mp |> filter(ano > 2017 & ano < 2023) |> select(-idade)

#junta bases

mdip <- merge(mdip_mp17, mdip_ssp17, by= "var_join", all=TRUE)

# Retira as linhas duplicadas

mdip <- mdip |> 
  distinct(data_nascimento_pessoa, var_join, .keep_all = TRUE)

#cria coluna COP (se o batalhão usa COP)

mdip_total <- mdip |> 
  mutate(COP = case_when
  (batalhao %in% c("07º BPM/M", "7º BPM/M", "11º BPM/M", "13º BPM/M", "07º BAEP", "7º BAEP",
                   "03º BPM/M", "3º BPM/M", "12º BPM/M", "46º BPM/M", "05º BPM/M", "5º BPM/M",
                   "09º BPM/M", "9º BPM/M", "18º BPM/M", "43º BPM/M", "02º BPM/M", "2º BPM/M", 
                   "29º BPM/M", "39º BPM/M", "48º BPM/M", "04º BAEP", "4º BAEP", "04º BPM/M",  
                   "4º BPM/M", "4º BPM/M", "49º BPM/M", "19º BPM/M", "28º BPM/M", "38º BPM/M", 
                   "01º BPM/M", "1º BPM/M", "22º BPM/M", "27º BPM/M", "37º BPM/M", "50º BPM/M", 
                   "16º BPM/M", "23º BPM/M", "08º BPM/M", "8º BPM/M", "21º BPM/M", "2º BPChoque",
                   "2º BPCh", "1º BPChoque (ROTA)", "1º BPChoque (Rota)", "1º BPCh e 49ºBPM/M",
                   "1º BPCh e 28º BPM/M", "1º BPCh (ROTA)", "1º BPCh (Rota)", "1º BPCh - ROTA",
                   "1º BPCh-ROTA", "6º BPM/M", "06º BPM/M", "10º BPM/M", "24º BPM/M", "30º BPM/M", 
                   "6º BAEP", "15º BPM/M", "26º BPM/M", "31º BPM/M", "15º BAEP", "14º BPM/M", 
                   "20º BPM/M", "25º BPM/M", "33º BPM/M", "36º BPM/M", "5º BAEP", "05º BAEP", 
                   "17º BPM/M", "32º BPM/M", "35º BPM/M", "46º BPM/I", "03º BAEP", "3º BAEP", 
                   "08º BPM/I","8º BPM/I", "21º BPM/I", "48º BPM/I", "2º BAEP", "02º BAEP",  
                   "1º BAEP",  "01º BAEP", "03º BAEP", "3º BAEP", "1º BPRv", "01º BPRv", 
                   "6º BPRv", "APMBB", "ESSgt", "ESSd", "EEF", "CAvPM") ~ "SIM",
    TRUE ~ "NÃO"))


# Cria variável com as faixas etárias

mdip_total <- mdip_total |> 
  mutate(situacao = case_when(
   situacao == "Serviço"~ "serviço", 
 TRUE ~ as.character(situacao)))

mdip_total <- mdip_total |>
  mutate(idade_pessoa_agregada = case_when(
    idade_pessoa > 0 & idade_pessoa < 04 ~ "0-04",
    idade_pessoa >= 05 & idade_pessoa <= 09 ~ "05-09",
    idade_pessoa >= 10 & idade_pessoa <= 14 ~ "10-14",
    idade_pessoa >= 15 & idade_pessoa <= 19 ~ "15-19",
    idade_pessoa >= 20 & idade_pessoa <= 24 ~ "20-24",
    idade_pessoa >= 25 & idade_pessoa <= 29 ~ "25-29",
    idade_pessoa >= 30 & idade_pessoa <= 34 ~ "30-34",
    idade_pessoa >= 35 & idade_pessoa <= 39 ~ "35-39",
    idade_pessoa >= 40 & idade_pessoa <= 44 ~ "40-44",
    idade_pessoa >= 45 & idade_pessoa <= 49 ~ "45-49",
    idade_pessoa >= 50 & idade_pessoa <= 54 ~ "50-54",
    idade_pessoa >= 55 & idade_pessoa <= 59 ~ "55-59",
    idade_pessoa >= 60 & idade_pessoa <= 64 ~ "60-64",
    idade_pessoa >= 65 ~ "65+")) |> 
    mutate(cor_pele_agregada = case_when(
      cor_pele %in% c("Parda","Preta") ~ "Negra",
      cor_pele %in% c("Outros", "NULL","Amarela",
"Ignorada","REGISTRADO NA PF","Policia Federal") ~ "NA",
      TRUE ~ as.character (cor_pele)))


```


```{r salva rds bancos, echo=FALSE, warning=FALSE}
saveRDS(mdip_ssp, "../data-raw/mdip_ssp.rds")
saveRDS(mdip_mp, "../data-raw/mdip_mp.rds")
saveRDS(mdip_total, "../data-raw/mdip_total.rds")

# Gera excel para verificarmos inconsistencias na base mdip_total

writexl::write_xlsx(mdip_total, "../data-raw/mdip_total.xlsx")

```

