## Recodificação municipios 

library(tidyverse)
mdip_ssp <- readRDS("../data-raw/mdip_ssp.rds")
mdip_mp <- readRDS("../data-raw/mdip_mp.rds")


#base ssp
unique(mdip_ssp$municipio_circunscricao)
[1] "S.PAULO"                                
[2] "S.BERNARDO DO CAMPO"                    
[3] "S.VICENTE"                              
[4] "ITAQUAQUECETUBA"                        
[5] "COSMOPOLIS"                             
[6] "ITAPEVI"                                
[7] "GUARUJA"                                
[8] "DIADEMA"                                
[9] "RIBEIRAO PRETO"                         
[10] "CAPIVARI"                               
[11] "SANTOS"                                 
[12] "OSASCO"                                 
[13] "ITAPECERICA DA SERRA"                   
[14] "ITATIBA"                                
[15] "BAURU"                                  
[16] "PIRACICABA"                             
[17] "GUARULHOS"                              
[18] "CAMPINAS"                               
[19] "REGISTRADO NA PF"                       
[20] "FRANCO DA ROCHA"                        
[21] "IACRI"                                  
[22] "CANANEIA"                               
[23] "JUNDIAI"                                
[24] "CUBATAO"                                
[25] "SOROCABA"                               
[26] "PRAIA GRANDE"                           
[27] "PERUIBE"                                
[28] "SUMARE"                                 
[29] "HORTOLANDIA"                            
[30] "PONTAL"                                 
[31] "INDAIATUBA"                             
[32] "S.JOSE DO RIO PRETO"                    
[33] "TABOAO DA SERRA"                        
[34] "ARARAQUARA"                             
[35] "RIBEIRAO PIRES"                         
[36] "MAUA"                                   
[37] "S.SEBASTIAO"                            
[38] "JACAREI"                                
[39] "AURIFLAMA"                              
[40] "ITAPEVA"                                
[41] "MOGI DAS CRUZES"                        
[42] "BARUERI"                                
[43] "S.ANDRE"                                
[44] "FERRAZ DE VASCONCELOS"                  
[45] "ILHABELA"                               
[46] "IGUAPE"                                 
[47] "TIETE"                                  
[48] "CARAPICUIBA"                            
[49] "MONTE MOR"                              
[50] "CARAGUATATUBA"                          
[51] "POA"                                    
[52] "IPIGUA"                                 
[53] "JARDINOPOLIS"                           
[54] "IRACEMAPOLIS"                           
[55] "NOVA ODESSA"                            
[56] "S.JOSE DOS CAMPOS"                      
[57] "BRAGANCA PAULISTA"                      
[58] "BOTUCATU"                               
[59] "S.CARLOS"                               
[60] "FRANCA"                                 
[61] "BERTIOGA"                               
[62] "BARRINHA"                               
[63] "COTIA"                                  
[64] "IBITINGA"                               
[65] "ARUJA"                                  
[66] "PITANGUEIRAS"                           
[67] "GUARACAI"                               
[68] "VALINHOS"                               
[69] "CONCHAS"                                
[70] "CANDIDO MOTA"                           
[71] "SERTAOZINHO"                            
[72] "JANDIRA"                                
[73] "GUARARAPES"                             
[74] "MAIRIPORA"                              
[75] "PRESIDENTE PRUDENTE"                    
[76] "EMBU"                                   
[77] "ARARAS"                                 
[78] "SUZANO"                                 
[79] "REGISTRO"                               
[80] "S.JOAQUIM DA BARRA"                     
[81] "RIO CLARO"                              
[82] "S.CAETANO DO SUL"                       
[83] "PALMITAL"                               
[84] "CACHOEIRA PAULISTA"                     
[85] "CAPAO BONITO"                           
[86] "VARGEM GRANDE PAULISTA"                 
[87] "MIRASSOL"                               
[88] "PINDAMONHANGABA"                        
[89] "MANDURI"                                
[90] "CARDOSO"                                
[91] "JARINU"                                 
[92] "TATUI"                                  
[93] "MOGI-GUACU"                             
[94] "MONGAGUA"                               
[95] "MARILIA"                                
[96] "BIRIGUI"                                
[97] "NOVA GRANADA"                           
[98] "AVARE"                                  
[99] "PIRACAIA"                               
[100] "TAUBATE"                                
[101] "GUARIBA"                                
[102] "FRANCISCO MORATO"                       
[103] "RIO DAS PEDRAS"                         
[104] "BROTAS"                                 
[105] "ITAPETININGA"                           
[106] "IPEUNA"                                 
[107] "LOUVEIRA"                               
[108] "GUARATINGUETA"                          
[109] "PIRAJU"                                 
[110] "CRISTAIS PAULISTA"                      
[111] "VINHEDO"                                
[112] "POLÍCIA FEDERAL Inquérito da PF 1082/14"
[113] "EMBU-GUACU"                             
[114] "CATANDUVA"                              
[115] "CAIEIRAS"                               
[116] "S.GERTRUDES"                            
[117] "PIEDADE"                                
[118] "MARACAI"                                
[119] "BOM JESUS DOS PERDOES"                  
[120] "LEME"                                   
[121] "S.CRUZ DA CONCEICAO"                    
[122] "VOTORANTIM"                             
[123] "LIMEIRA"                                
[124] "CERQUILHO"                              
[125] "ARACOIABA DA SERRA"                     
[126] "SERRA AZUL"                             
[127] "IPAUSSU"                                
[128] "BARRETOS"                               
[129] "S.ROSA DE VITERBO"                      
[130] "PORTO FELIZ"                            
[131] "TORRE DE PEDRA"                         
[132] "S.ISABEL"                               
[133] "ARACARIGUAMA"                           
[134] "CAMPO LIMPO PAULISTA"                   
[135] "POLÍCIA FEDERAL Inquérito da PF 1658/14"
[136] "PALESTINA"                              
[137] "ELIAS FAUSTO"                           
[138] "LENCOIS PAULISTA"                       
[139] "BURI"                                   
[140] "CESARIO LANGE"                          
[141] "VIRADOURO"                              
[142] "ATIBAIA"                                
[143] "MOCOCA"                                 
[144] "SANTA MARIA DA SERRA"                   
[145] "UBATUBA"                                
[146] "LARANJAL PAULISTA"                      
[147] "PILAR DO SUL"                           
[148] "SALTINHO"                               
[149] "CACAPAVA"                               
[150] "JAU"                                    
[151] "REGISTRADO NA PF - BO 200/15"           
[152] "INUBIA PAULISTA"                        
[153] "PAULO DE FARIA"                         
[154] "PATROCINIO PAULISTA"                    
[155] "ARACATUBA"                              
[156] "ITU"                                    
[157] "ITAI"                                   
[158] "PAULINIA"                               
[159] "S.BARBARA D OESTE"                      
[160] "ITUPEVA"                                
[161] "ITANHAEM"                               
[162] "PORTO FERREIRA"                         
[163] "VARZEA PAULISTA"                        
[164] "TAPIRAI"                                
[165] "CAJAMAR"                                
[166] "TAQUARITINGA"                           
[167] "BIRITIBA-MIRIM"                         
[168] "FLORIDA PAULISTA"                       
[169] "S.ROQUE"                                
[170] "DUMONT"                                 
[171] "GUARAREMA"                              
[172] "ITIRAPINA"                              
[173] "MURUTINGA DO SUL"                       
[174] "S.MIGUEL ARCANJO"                       
[175] "JABOTICABAL"                            
[176] "S.CRUZ DAS PALMEIRAS"                   
[177] "PIRAPOZINHO"                            
[178] "ANDRADINA"                              
[179] "OLIMPIA"                                
[180] "BARRA DO TURVO"                         
[181] "NOVA EUROPA"                            
[182] "AGUAI"                                  
[183] "POTIRENDABA"                            
[184] "ARTUR NOGUEIRA"                         
[185] "JOSE BONIFACIO"                         
[186] "ITARIRI"                                
[187] "VOTUPORANGA"                            
[188] "ITUVERAVA"                              
[189] "VALENTIM GENTIL"                        
[190] "ORLANDIA"                               
[191] "BEBEDOURO"                              
[192] "JUQUIA"                                 
[193] "PRESIDENTE EPITACIO"                    
[194] "LORENA"                                 
[195] "ESPIRITO STO. PINHAL"                   
[196] "ASSIS"                                  
[197] "PARAGUACU PAULISTA"                     
[198] "JUQUITIBA"                              
[199] "ITAPIRA"                                
[200] "MONTE APRAZIVEL"                        
[201] "AGUDOS"                                 
[202] "ITAJOBI"                                
[203] "SALTO"                                  
[204] "ITAPIRAPUA PAULISTA"                    
[205] "SANTANA DE PARNAIBA"                    
[206] "REGISTRADO NA PF - BO 1114/16"          
[207] "FARTURA"                                
[208] "MACATUBA"                               
[209] "SÃO MANUEL"                             
[210] "MAIRINQUE"                              
[211] "LAVRINHAS"                              
[212] "IGARATA"                                
[213] "RIFAINA"                                
[214] "TERRA ROXA"                             
[215] "LAVINIA"                                
[216] "VARGEM"                                 
[217] "TAQUARITUBA"                            
[218] "BOFETE"                                 
[219] "MIRACATU"                               
[220] "ILHA COMPRIDA"                          
[221] "ONDA VERDE"                             
[222] "UCHOA"                                  
[223] "MINEIROS DO TIETE"                      
[224] "CAFELANDIA"                             
[225] "IBIUNA"                                 
[226] "ALVARES MACHADO"                        
[227] "CAPELA DO ALTO"                         
[228] "GUARÁ"                                  
[229] "S.LUIS DO PARAITINGA"                   
[230] "LOURENÇO DA SERRA"                      
[231] "PRACINHA"                               
[232] "REGISTRADO EM (MG)"                     
[233] "MATAO"                                  
[234] "CAJATI"                                 
[235] "AMERICANA"                              
[236] "TANABI"                                 
[237] "REGISTRADO NA PF - BO 206/17"           
[238] "CORUMBATAI"                             
[239] "RIO GRANDE DA SERRA"                    
[240] "CHARQUEADA"                             
[241] "CEDRAL"                                 
[242] "ALVINLÂNDIA"                            
[243] "GUZOLÂNDIA"                             
[244] "BATATAIS"                               
[245] "S.SIMAO"                                
[246] "RIBEIRAO BRANCO"                        
[247] "PIRAPORA DO BOM JESUS"                  
[248] "MOGI-MIRIM"                             
[249] "JAMBEIRO"                               
[250] "GUAIRA"                                 
[251] "SAO JOAO DA BOA VISTA"                  
[252] "PONGAI"                                 
[253] "GAVIÃO PEIXOTO"                         
[254] "ARIRANHA"                               
[255] "IBATÉ"                                  
[256] "GUAREI"                                 
[257] "CATIGUA"                                
[258] "SABINO"                                 
[259] "TREMEMBE"                               
[260] "OURINHOS"                               
[261] "BADY BASSIT"                            
[262] "MOMBUCA"                                
[263] "S.PEDRO"                                
[264] "ELDORADO"                               
[265] "TORRINHA"                               
[266] "ENGENHEIRO COELHO"                      
[267] "POLONI"                                 
[268] "SALESOPOLIS"                            
[269] "CRUZEIRO"                               
[270] "ROSANA"                                 
[271] "CONCHAL"                                
[272] "MARTINOPOLIS"                           
[273] "ELISIÁRIO"                              
[274] "RIBEIRAO GRANDE"                        
[275] "BOITUVA"                                
[276] "IPERÓ"                                  
[277] "LINS"                                   
[278] "MORRO AGUDO"                            
[279] "PARIQUERA-ACU"                          
[280] "AGUAS DE S. BARBARA"                    
[281] "JACI"                                   
[282] "CAMPOS DO JORDAO"                       
[283] "PRADOPOLIS"                             
[284] "RINCAO"                                 
[285] "PEDREGULHO"                             
[286] "PEDERNEIRAS"                            
[287] "BARRA BONITA"                           
[288] "SALTO DE PIRAPORA"                      
[289] "JACUPIRANGA"                            
[290] "BASTOS"                                 
[291] "QUATA"                                  
[292] "ALTAIR"                                 
[293] "PIQUETE"                                
[294] "NEVES PAULISTA"                         
[295] "SERRA NEGRA"                            
[296] "CABRÁLIA PAULISTA"                      
[297] "IEPÊ"                                   
[298] "PEDRO DE TOLEDO"                        
[299] "IBIRA"                                  
[300] "CAMPOS NOVOS PAUL."                     
[301] "NAZARE PAULISTA"                        
[302] "SETE BARRAS"                            
[303] "PANORAMA"                               
[304] "CRIME MILITAR"                          
[305] "TUPA"                                   
[306] "PAULICEIA"                              
[307] "RINOPOLIS"                              
[308] "SOCORRO"                                
[309] "GAVIAO PEIXOTO"                         
[310] "SERRANA"                                
[311] "FERNANDOPOLIS"                          
[312] "JAGUARIUNA"                             
[313] "CORONEL MACEDO"                         
[314] "NOVA ALIANCA"                           
[315] "CASA BRANCA"                            
[316] "ARAPEI"                                 
[317] "Policia Federal"                        
[318] "BURITAMA"                               
[319] "IPERO"                                  
[320] "DESCALVADO"                             
[321] "NUPORANGA"                              
[322] "APIAI"                                  
[323] "ANHEMBI"                                
[324] "ADAMANTINA"                             
[325] "GUAPIACU"                               
[326] "MERIDIANO"                              
[327] "SALES OLIVEIRA"                         
[328] "PRESIDENTE BERNARDES"                   
[329] "S.CRUZ DO RIO PARDO"                    
[330] "RUBIACEA"                               
[331] "ITOBI"

#base mp
unique(mdip_mp$cidade)

[1] "ITAPECERICA DA SERRA"     "SANTO ANDRÉ"             
[3] "RIO CLARO"                "UBATUBA"                 
[5] "RIBEIRÃO PRETO"           "SÃO PAULO"               
[7] "FERRAZ DE VASCONCELOS"    "GUARUJÁ"                 
[9] "GUARULHOS"                "SÃO BERNARDO DO CAMPO"   
[11] "FARTURA"                  "PRAIA GRANDE"            
[13] "SUMARÉ"                   "MACATUBA"                
[15] "CUBATÃO"                  "LORENA"                  
[17] "SÃO MANUEL"               "SÃO VICENTE"             
[19] "OSASCO"                   "SOROCABA"                
[21] "EMBU-GUAÇU"               "SUZANO"                  
[23] "ITU"                      "MAUÁ"                    
[25] "ITAQUAQUECETUBA"          "SERTÃOZINHO"             
[27] "TABOÃO DA SERRA"          "HORTOLÂNDIA"             
[29] "EMBU DAS ARTES"           "BAURU"                   
[31] "CAMPINAS"                 "SÃO JOSÉ DOS CAMPOS"     
[33] "DIADEMA"                  "MAIRINQUE"               
[35] "LAVRINHAS"                "ATIBAIA"                 
[37] "SANTOS"                   "VOTORANTIM"              
[39] "CARAPICUÍBA"              "ITAPEVI"                 
[41] "PINDAMONHANGABA"          "JACAREÍ"                 
[43] "IACRI"                    "MOGI DAS CRUZES"         
[45] "LARANJAL PAULISTA"        "POÁ"                     
[47] "AGUAÍ"                    "ITATIBA"                 
[49] "IGARATÁ"                  "PIRACICABA"              
[51] "RIFAINA"                  "ESPÍRITO SANTO DO PINHAL"
[53] "SÃO JOSÉ DO RIO PRETO"    "COTIA"                   
[55] "ITANHAÉM"                 "CAIEIRAS"                
[57] "BARUERI"                  "SANTANA DE PARNAÍBA"     
[59] "AGUDOS"                   "PONTAL"                  
[61] "CAPIVARI"                 "SÃO ROQUE"               
[63] "ARARAS"                   "PRESIDENTE PRUDENTE"     
[65] "VÁRZEA PAULISTA"          "PERUÍBE"                 
[67] "TAQUARITUBA"              "LIMEIRA"                 
[69] "CAÇAPAVA"                 "BOFETE"                  
[71] "MIRACATU"                 "SALTO"                   
[73] "CARAGUATATUBA"            "MAIRIPORÃ"               
[75] "BEBEDOURO"                "AMERICANA"               
[77] "LEME"                     "ARUJÁ"                   
[79] "ILHA COMPRIDA"            "MONTE MOR"               
[81] "ONDA VERDE"               "ARAÇATUBA"               
[83] "MINEIROS DO TIETÊ"        "SÃO CAETANO DO SUL"      
[85] "ÁLVARES MACHADO"          "TAUBATÉ"                 
[87] "JUNDIAÍ"                  "CAPELA DO ALTO"          
[89] "ITUPEVA"                  "PRACINHA"                
[91] "RIBEIRÃO PIRES"           "INDAIATUBA"              
[93] "MATÃO"                    "FRANCO DA ROCHA"         
[95] "CAJATI"                   "TANABI"                  
[97] "ITAPETININGA"             "CORUMBATAÍ"              
[99] "CAMPO LIMPO PAULISTA"     "MONGAGUÁ"                
[101] "RIO GRANDE DA SERRA"      "CHARQUEADA"              
[103] "FRANCISCO MORATO"         "VALINHOS"                
[105] "SANTA ISABEL"             "BERTIOGA"                
[107] "SÃO CARLOS"               "BARRINHA"                
[109] "JARDINÓPOLIS"             "CEDRAL"                  
[111] "GUARATINGUETÁ"            "ALVINLÂNDIA"             
[113] "BATATAIS"                 "GUZOLÂNDIA"              
[115] "MARÍLIA"                  "BOTUCATU"                
[117] "SÃO SIMÃO"                "RIBEIRÃO BRANCO"         
[119] "COSMÓPOLIS"               "INÚBIA PAULISTA"         
[121] "ARAÇOIABA DA SERRA"       "FLÓRIDA PAULISTA"        
[123] "BARRETOS"                 "PAULÍNIA"                
[125] "PIRAPORA DO BOM JESUS"    "JAÚ"                     
[127] "JAMBEIRO"                 "GUAÍRA"                  
[129] "PONGAÍ"                   "ARARAQUARA"              
[131] "ASSIS"                    "APIAÍ"                   
[133] "GAVIÃO PEIXOTO"           "ARIRANHA"                
[135] "IBATÉ"                    "JARINU"                  
[137] "CÂNDIDO MOTA"             "GUAREÍ"                  
[139] "CAJAMAR"                  "CERQUILHO"               
[141] "SANTA BÁRBARA D'OESTE"    "BRAGANÇA PAULISTA"       
[143] "CATIGUÁ"                  "SABINO"                  
[145] "TREMEMBÉ"                 "OURINHOS"                
[147] "BADY BASSITT"             "MOMBUCA"                 
[149] "SÃO PEDRO"                "TATUÍ"                   
[151] "ARTUR NOGUEIRA"           "JUQUITIBA"               
[153] "TORRINHA"                 "OLÍMPIA"                 
[155] "FRANCA"                   "BOM JESUS DOS PERDÕES"   
[157] "NOVA ODESSA"              "PIRASSUNUNGA"            
[159] "ENGENHEIRO COELHO"        "CRUZEIRO"                
[161] "POLONI"                   "SALESÓPOLIS"             
[163] "ROSANA"                   "CONCHAL"                 
[165] "MONTE APRAZÍVEL"          "MARTINÓPOLIS"            
[167] "PAULO DE FARIA"           "ELISIÁRIO"               
[169] "SÃO SEBASTIÃO"            "BARRA DO TURVO"          
[171] "RIBEIRÃO GRANDE"          "BOITUVA"                 
[173] "IPERÓ"                    "PORTO FERREIRA"          
[175] "GUARAREMA"                "MORRO AGUDO"             
[177] "MOGI MIRIM"               "ITARIRI"                 
[179] "ITAÍ"                     "PARIQUERA-AÇU"           
[181] "ÁGUAS DE SANTA BÁRBARA"   "JACI"                    
[183] "SÃO LOURENÇO DA SERRA"    "CAMPOS DO JORDÃO"        
[185] "REGISTRO"                 "PRADÓPOLIS"              
[187] "MOGI GUAÇU"               "DRACENA"                 
[189] "ITIRAPINA"                "VARGEM GRANDE PAULISTA"  
[191] "JANDIRA"                  "RINCÃO"                  
[193] "IBIÚNA"                   "PEDREGULHO"              
[195] "PEDERNEIRAS"              "SANTA CRUZ DAS PALMEIRAS"
[197] "AVARÉ"                    "SALTO DE PIRAPORA"       
[199] "ARAÇARIGUAMA"             "GUARARAPES"              
[201] "LOUVEIRA"                 "ALTINÓPOLIS"             
[203] "MAiRIPORÃ"                "QUELUZ"                  
[205] "BASTOS"                   "QUATÁ"                   
[207] "ALTAIR"                   "PIQUETE"                 
[209] "BIRITIBA MIRIM"           "NEVES PAULISTA"          
[211] "TAQUARITINGA"             "SERRA NEGRA"             
[213] "CABRÁLIA PAULISTA"        "IEPÊ"                    
[215] "PEDRO DE TOLEDO"          "IBIRÁ"                   
[217] "CAMPOS NOVOS PAULISTA"    "NAZARÉ PAULISTA"         
[219] "SETE BARRAS"              "BORBOREMA"               
[221] "PANORAMA"                 "JACUPIRANGA"             
[223] "TUPÃ"                     "PORTO FELIZ"             
[225] "ITAPIRA"                  "PAULICÉIA"               
[227] "ELIAS FAUSTO"             "RINÓPOLIS"               
[229] "SOCORRO"                  "SERRANA"                 
[231] "FERNANDÓPOLIS"            "CAMPOS NOVOS PAULISTAS"  
[233] "ÁGUAS DE LINDÓIA"         "IBIUNA"                  
[235] "JAGUARIÚNA"               "CORONEL MACEDO"          
[237] "JABOTICABAL"              "NOVA ALIANÇA"            
[239] "PILAR DO SUL"             "CASA BRANCA"             
[241] "CANANÉIA"                 "ARAPEÍ"                  
[243] "BURITAMA"                 "DESCALVADO"              
[245] "CONCHAS"                  "VOTUPORANGA"             
[247] "MARACAÍ"                  "ANHEMBI"                 
[249] "NUPORANGA"                "ADAMANTINA"              
[251] "GUAPIAÇU"                 "BIRIGUI"                 
[253] "CERQUEIRA CÉSAR"          "MERIDIANO"               
[255] "BURI"                     "PRESIDENTE BERNARDES"    
[257] "SALES OLIVEIRA"           "SANTA FÉ DO SUL"         
[259] "LENÇÓIS PAULISTA"         "IACANGA"                 
[261] "OSVALDO CRUZ"             "ORLÂNDIA"                
[263] "PINHALZINHO"              "PITANGUEIRAS"            
[265] "BERNARDINO DE CAMPOS"     "ITOBI"   


#código 

mdip_mp %>%  mutate (municipio_limpo = case_when(
  cidade == "S.PAULO" ~ "SÃO PAULO",
  cidade == "nome_antigo" ~ "nome_novo",
  
  
  
  TRUE = as.character(cidade)
))