---
title: "Análises MDIP/ Sou da Paz Analisa 2013-2022"
author: "Instituto Sou da Paz"
date: '2022-02-23'
output:
  html_document: default
  pdf_document: default
---
```{r setup, message=FALSE, include=FALSE, warning=FALSE}
library(tidyverse)
library(janitor)
library(rio)
library(knitr)
library(kableExtra)
library(ggrepel)
library(hrbrthemes)
library(readxl)
    
```

```{r bancos mdip, echo=FALSE, warning=FALSE}

mdip_ssp <- readRDS("../data-raw/mdip_ssp.rds")
mdip_mp <- readRDS("../data-raw/mdip_mp.rds")

```
 
**situação (folga ou serviço)**.


```{r descritivas}

mdip_mp  |>  group_by(batalhao) |> summarise(total = n()) |> arrange(desc(total)) |> mutate(mean= mean(total), sd = sd(total)) |>   view()

mdip_mp %>% group_by (ano) %>% count()
mdip_ssp %>%group_by(ano_estatistica) %>% count()

 unique(mdip_mp$vitimas)


```
A base do MP apresenta 447 casos de MDIP em 2022, já  a base da SSP registrou 419 casos no mesmo ano.
Em 2021 a base do MP registrou 555 casos, já a da SSP, 570. Em 2020 a a do MP 732 contra 814 casos presentes na base da SSP.


```{r  situação e cor_peleporação, include= FALSE}
mdip_ssp <- mdip_ssp %>% 
  mutate(situacao = case_when( situacao == "folga" ~ "Folga",
                                  situacao == "serviço" ~ "Serviço",
                                  situacao == "Folga" ~ "Folga",
                                  situacao == "Serviço" ~"Serviço"))  

mdip_ssp <- mdip_ssp %>% 
  mutate (coorporacao = case_when (coorporacao == "PC" ~ "Polícia Civil",
                                   coorporacao == "PM" ~ "Polícia Militar")) 



## Gráficos
### Série Histórica Situação
gs<- mdip_ssp |> 
  count(ano_estatistica, situacao) %>%  
  ggplot(aes(x = ano_estatistica, y = n, color = situacao)) +
  geom_line(size= 1.5)+
  scale_color_brewer ( palette ="Set1") +
  labs(x = "Ano", y= "Frequência", color = "Situação", 
       title = "MDIP por Situação", subtitle = "2016-2021")+
  theme_minimal()

gs
## Série Histórica por cor_peleporação 2016-2021

gc<- mdip_ssp %>% 
  count(ano_estatistica, coorporacao) %>% 
  ggplot(aes(x = ano_estatistica, y = n, color= coorporacao)) +
  geom_line(size= 1) +
  scale_color_brewer ( type = "seq", palette ="Set2") +
  labs(x = "Ano", y= "Frequência", color = "cor_peleporação", 
       title = "MDIP por cor_peleporação", subtitle = "2016-2021")+
  theme_minimal()


gc
## cor_peleporação 1o trimestre 2016-2022
gct<- mdip_ssp %>% 
  mutate(mes_estatistica = case_when( mes_estatistica < 4 ~ "1o trimestre",
                                      between(mes_estatistica, 3,6) ~ "2o trimestre",
                                      between(mes_estatistica, 7,9) ~ "3o trimestre",
                                      between(mes_estatistica, 10,12)~"4o trimetre")) |>
  group_by(mes_estatistica, coorporacao) |> 
summarise(n = n()) |> 
  ggplot(aes(x = mes_estatistica, y=n, fill= coorporacao, label = n)) +
  geom_bar(stat = "identity", position = "dodge") +
    geom_label_repel(fill = "white")+
  labs(x = "", y= "Frequência", fill = "cor_peleporação",  
  title = "MDIP por cor_peleporação em 2022", subtitle = "")+
  scale_fill_viridis(discrete=TRUE, option = "D") +
    theme_ipsum()
gct



## Situação 1o Trimestre 2016-2022
gst <- mdip_ssp %>% filter (mes_estatistica <= 4) %>% 
  count(ano_estatistica, situacao) %>%  
   ggplot(aes(x = ano_estatistica, y = n, fill= situacao)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_color_brewer ( palette ="Set1") +
  labs(x = "Ano", y= "Frequência", color = "Situação", 
       title = "MDIP por Situação no Primeiro Trimestre", "2016-2022")+
  theme_minimal()

gst
## Situação do Evento por cor_peleporação no Estado de São Paulo
gsc_est <- mdip_ssp |>  
   ggplot(aes(x = ano_estatistica, fill = situacao )) + 
  geom_bar(stat = "count", position = "dodge") +
  facet_wrap(~coorporacao) +
  scale_color_brewer(palette ="Set2") +
  coord_flip()+
  labs(x = "Ano", y= "Frequência", fill = "Situação", title = "Situação por cor_peleporação no Estado de São Paulo", "2016-2020")
  theme_minimal()

```

**Tabelas** 

```{r tabs, echo=FALSE}
##Tabelas
kable (mdip %>% 
   filter (ano !=2022) %>%
  tabyl(situacao, cor_peleporacao) %>% 
adorn_totals("row") %>% 
  adorn_percentages("col") %>% 
  adorn_pct_formatting(affix_sign = FALSE) %>% 
  adorn_ns(),
col.names = c("Situação", "Polícia Civil", "Polícia Militar")) %>% 
  kable_styling(full_width = F, bootstrap_options = c("striped", "hover","condensed", "responsive"))

```

```{r tabelas, echo=FALSE}


kable(mdip %>%  
  filter (ano !=2022) %>% 
  tabyl(ano, cor_peleporacao) %>% 
  adorn_totals("row") %>% 
  adorn_percentages("col") %>% 
  adorn_pct_formatting(affix_sign = FALSE) %>% 
  adorn_ns(),
col.names = c("Ano", "Polícia Civil", "Polícia Militar" )) %>% kable_styling(full_width = F, bootstrap_options = c("striped", "hover","condensed", "responsive"))


```

**Gráficos**
```{r graficos, out.width= "80%",fig.align = "center", echo=FALSE}
gs + scale_y_continuous (expand = expansion (add = c(0,300)))+
  scale_x_continuous(breaks = 2016:2022)

gc + scale_y_continuous (expand = expansion (add = c(0,300)))+
scale_x_continuous(breaks = 2016:2022)

gct + scale_y_continuous (expand = expansion (add = c(0,500)))+ scale_x_continuous(breaks = 2016:2022)

gst + scale_y_continuous (expand = expansion (add = c(0,400)))+
scale_x_continuous(breaks = 2016:2022)

gsc_est + scale_y_continuous (expand = expansion (add = c(0,300)))+
  scale_x_continuous(breaks = 2016:2022)
```


```{r recodificação, echo=FALSE}
mdip <- mdip %>% 
  mutate ( cor_pele = case_when(cor_pele == "Amarela" ~ "Amarela",
                              cor_pele == "Branca" ~ "Branca",
                              cor_pele == "Parda" ~ "Negra",
                              cor_pele == "Preta" ~"Negra",
                              cor_pele == "Outros" ~"Outros",
                              cor_pele == "REGISTRADO NA PF" ~ "Outros",
                              cor_pele == "NÃO INFORMADO" ~ "Não Informada", 
                              TRUE = as.character(cor_pele))) 

mdip<- mdip %>% 
  mutate( sexo_pessoa = case_when(sexo_pessoa == "Feminino" ~ "Feminino",
                              sexo_pessoa == "Masculino" ~ "Masculino",
                              sexo_pessoa == "Indefinido" ~ "Outros",
                              sexo_pessoa == "NÃO INFORMADO" ~"Não Informado",
                              sexo_pessoa == "REGISTRADO NA PF" ~"Outros"))

mdip <- mdip %>% 
  filter (idade_pessoa !="NÃO INFORMADO") %>% 
   filter (idade_pessoa !="REGISTRADO NA PF") %>%
  mutate(idade_pessoa = case_when(idade_pessoa %in% 0:14  ~ "0-14",
                                  idade_pessoa %in% 15:24 ~ "15-24",
                                  idade_pessoa %in% 25:34 ~ "25-34",
                                  idade_pessoa %in% 35:44 ~ "35-44",
                                  idade_pessoa %in% 45:54 ~ "45-54",
                                  idade_pessoa %in% 55:64 ~ "55-64",
                                  idade_pessoa >= 65 ~ "65 ou mais"))



gsex<- mdip %>% 
  count(sexo_pessoa) |> 
  filter(sexo_pessoa %in% c("Feminino", "Masculino")) %>% 
  ggplot(aes(x = sexo_pessoa,y =n, fill = sexo_pessoa, label =n)) + 
  geom_col() +
  geom_label_repel(fill = "white")+
  scale_fill_brewer (type= "div" , palette ="Set1") +
  labs(x = "Sexo", y= "Frequência", fill = "Sexo", title = "Sexo das Vítimas", subtitle =  "2016-2022")+
  theme_minimal()

gcor_pele<- mdip %>% 
  group_by(cor_pele, ano_estatistica) |> 
summarise(total = n()) |>
  mutate(freq= paste0(round(total/sum(total)*100))) |> 
  ggplot(aes(x = reorder(cor_pele,freq), y= freq,  fill = cor_pele, label = freq))+ 
  geom_col() +
  geom_label_repel(fill = "white")+
   scale_fill_brewer ( palette ="Set2") +
   facet_wrap(~ ano_estatistica)+
  labs(x = "Cor/Raça", y= "Frequência", fill = "cor_pele", title = "Cor/ Raça das Vítimas", subtitle =  "2016-2022")+
  theme_minimal()

gidad <- mdip |> 
  count(idade_pessoa, ano_estatistica) |> 
  mutate(freq = round(n/ sum(n)*100, 0), "%") |> 
  ggplot(aes(x = reorder(idade_pessoa, n), y= n, fill = idade_pessoa, label = n)) + 
  geom_col() +
  geom_label_repel(fill = "white")+
  scale_fill_brewer ( palette ="Dark2")+
  coord_flip()+
  labs(x = "Faixa etária", y= "Frequência", fill = "Faixa Etária", title = "Faixa Etária das Vítimas", subtitle =  "2016-2022")+
  facet_wrap(~ ano_estatistica)+
  theme_minimal()
```

```{r grafs cor, sex, id,fig.align = "center", echo=FALSE}
gsex + scale_y_continuous (expand = expansion (add = c(0,200))) + theme(legend.position = "none")
gcor_pele + scale_y_continuous (expand = expansion (add = c(0,200))) + theme(legend.position = "none")
gidad + scale_y_continuous (expand = expansion (add = c(0,100)))+
theme(legend.position = "none")

```

```{r perfil tabelas ,fig.align = "left", echo=FALSE}
###Tabela cor_pele
kable(mdip %>% tabyl(cor_pele)%>% 
  adorn_pct_formatting(affix_sign = FALSE), 
  col.names = c("cor_pele/ Raça", "Casos", "%")) %>% 
  kable_styling(full_width = F, bootstrap_options = c("striped", "hover", "condensed", "responsive"))

###Tabela sexo_pessoa
kable(mdip %>% tabyl(sexo_pessoa)%>% 
  adorn_pct_formatting(affix_sign = FALSE), 
  col.names = c("sexo_pessoa", "Casos", "%"))%>% 
  kable_styling(full_width = F, bootstrap_options = c("striped", "hover","condensed", "responsive"))

###Tabela idade_pessoa
kable(mdip %>% tabyl(idade_pessoa)%>%
  adorn_pct_formatting(affix_sign = FALSE), 
  col.names = c("Faixa Etária", "Casos", "%"))%>% 
  kable_styling(full_width = F, bootstrap_options = c("striped", "hover","condensed", "responsive"))
```

export(mdip, "mdip.rds")

```